# Generated by Django 4.2.7 on 2024-02-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='cart_id',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='billingprofile',
            old_name='last_4',
            new_name='last4',
        ),
    ]
